<?php
include('../../modelo/conexion.php');
session_start();
if(isset($_SESSION['k_username'])){
$query = mysql_query('SELECT * from pacientes where numero_doc="'.$_POST['id'].'" ');
$f = mysql_fetch_array($query);
$p = array();
$p[0] = $f['numero_doc'];
$p[1] = $f['nombres'];
$p[2] = $f['direccion1'];
$p[3] = $f['tel_1'];
$p[4] = $f['nombre_acudiente'];
$p[5] = $f['telefono_acudiente'];
$p[6] = $f['fecha_mod'];
$p[7] = $f['fecha_reg'];
$p[8] = $f['id_empresa'];
$p[9] = $f['departamento'];
//$p[10] = $f['municipio'];
$p[11] = $f['estado'];
$p[12] = $f['descripcion_enf'];
$p[13] = $f['subcodigo'];
$p[14] = $f['nombre2'];
$p[15] = $f['apellidos'];
$p[16] = $f['apellido2'];
$p[17] = $f['celular'];
$p[18] = $f['deposito_alq'];
$p[19] = $f['enfermedad'];
$p[20] = $f['ultima_atencion'];
$p[21] = $f['ultimo_alquiler'];
$p[22] = $f['regimen'];
$p[23] = $f['tipo_s'];
$p[24] = $f['sexo'];
$p[25] = $f['fecha_nacimiento'];
$p[26] = $f['civil'];
$p[27] = $f['ocupacion'];
$p[28] = $f['cedula_acudiente'];
$p[29] = $f['dir_pariente'];
$p[30] = $f['parentesco2'];
$p[31] = $f['parentesco'];
$p[32] = $f['diagnostico2'];
$p[33] = $f['descripcion_diag2'];
$p[34] = $f['tel_empresa'];
$p[35] = $f['barrio'];
$p[36] = $f['email1'];
$p[37] = $f['documento'];
$p[38] = $f['edad'];
$p[39] = $f['zona'];
$con= "SELECT * FROM `departamentos` where cod_dep='".$f['departamento']."' and cod_mun='".$f['municipio']."' ";
$res=  mysql_query($con);
$g = mysql_fetch_array($res);
$p[10] = $g['id'];
$p[40] = $f['contracto'];  
$p[41] = $f['covid']; 
$p[42] = $f['obscovid']; 
echo json_encode($p);
exit();
}