var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "ddMMyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "d/M/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index":1,
            "day_index": 0,
            "day": "d",
            "dom": "Dom",
            "lun": "Lun",
            "mar": "Mar",
            "mie": "Mie",
            "jue": "Jue",
            "vie": "Vie",
            "sab": "Sab",
            "ene": "Ene",
            "feb": "Feb",
            "mar": "Mar",
            "abr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "ago": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dic": "Dic"
        },
        "no_implemented": "No implementado",
        "to_date_view": "Click para ver fecha actual",
        "i_undefined": "Indefinido",
        "allday_event": "Por defecto (de 08:00 A 09:00)",
        "repeat_event": "Repetir Evento",
        "time": "Hora",
        "event": "Evento",
        "location": "Lugar",
        "participant": "Participantes",
        "get_data_exception": "Excepcion al obtener datos",
        "new_event": "Nuevo Evento",
        "confirm_delete_event": "Desea Eliminar este Evento? ",
        "confrim_delete_event_or_all": "Quieres este Evento O solo este Evento? \r\nClick [OK] a eliminar este evento, click [Cancel] Borrar todos los eventos",
        "data_format_error": "Data format error! ",
        "invalid_title": "el titulo del evento no puede estar en blanco ($<>)",
        "view_no_ready": "La vista no esta lista",
        "example": "ejemp., llamar a alguien",
        "content": "Asunto",
        "create_event": "Crear eventos",
        "update_detail": "Editar detalles",
        "click_to_detail": "Ver Detalles",
        "i_delete": "Eliminar",
        "day_plural": "dias",
        "others": "Otros",
        "item": ""
    }
});
